/**
 * action types
 */

export const HIDE_ALERT = 'HIDE_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const SAVE_MESSAGE_TITLE = 'SAVE_MESSAGE_TITLE';
export const SAVE_SELECTED_LOCATION = 'SAVE_SELECTED_LOCATION';
